-- ATEMA STUDIO — machine-generated catalogue backup
-- Snapshot of the live `packages` + `addons` tables, taken 2026-08-13T19:09:11.297Z.
--
-- This is a POINT-IN-TIME BACKUP, not an active seed. It is deliberately
-- NOT referenced by .github/workflows/supabase-migrations.yml, so running
-- migrations never applies it. To restore from this snapshot, run it by
-- hand via the Supabase SQL editor or a manual `only-file` workflow
-- dispatch — it is a safe idempotent UPSERT either way.
--
-- Generated by scripts/export-catalogue.mjs — do not hand-edit; re-run the
-- script to refresh instead.

insert into public.addons (id, name_ar, name_en, active, sort_order, price_sar, icon_emoji, description_ar, description_en, is_active, price)
values
  ('--1780506890141', 'تغطية جوال', 'Mobile Coverage ', true, 60, NULL, NULL, NULL, NULL, true, 1000),
  ('-1780431887832', 'وصيفة', 'Bridesmaid', true, 80, NULL, NULL, NULL, NULL, true, 700),
  ('album-upgrade', 'ترقية الألبوم إلى A3', 'Album upgrade to A3', true, 100, 800, NULL, NULL, NULL, true, 800),
  ('bridal-prep', 'تصوير تحضيرات العروس (ساعة ونصف)', 'Bridal prep session', true, 50, 1200, NULL, NULL, NULL, true, 1200),
  ('express-24h', 'تسليم فائق السرعة (24 ساعة)', 'Express Delivery (24h)', true, 100, 800, NULL, 'استلام صورك المعدلة خلال 24 ساعة من جلسة التصوير', 'Receive your edited photos within 24 hours of the shoot', true, 800),
  ('express-48h', 'تسليم سريع (48 ساعة)', 'Express Delivery (48h)', false, 100, 500, NULL, 'استلام صورك المعدلة خلال 48 ساعة من جلسة التصوير', 'Receive your edited photos within 48 hours of the shoot', true, 500),
  ('extra-hour', 'ساعة تصوير إضافية', 'Extra photo hour', true, 10, 700, NULL, 'ساعة تصوير إضافية مع المصورة', 'One additional hour of photography coverage', true, 900),
  ('extra-pages', 'صفحات ألبوم إضافية (سعر الصفحة)', 'Extra album page (per page)', true, 90, 120, NULL, NULL, NULL, true, 120),
  ('henna', 'تغطية ليلة الحناء (ساعتين)', 'Henna night coverage', true, 40, 2400, NULL, NULL, NULL, true, 2400),
  ('kosha', 'تصوير القاعة والضيافة قبل الحفل (٤٥ دقيقة)', 'Pre-event shoot', true, 50, 800, NULL, NULL, NULL, false, 800),
  ('makeup-styling', 'تنسيق مكياج وتصفيف', 'Makeup & Styling Coordination', true, 90, 1500, NULL, 'تنسيق مكياج وتصفيف شعر احترافي ليوم تصويرك', 'Professional makeup and hair styling coordination for your shoot day', true, 700),
  ('out-of-area-travel', 'تغطية خارج المنطقة الشرقية', 'Out-of-Area Travel Coverage', true, 100, 600, NULL, 'تغطية التصوير خارج المنطقة الشرقية (الجبيل، الدمام، الخبر، الظهران، القطيف، رأس تنورة)', 'Photography coverage outside the Eastern Province base area', true, 600),
  ('photo-pack-10', 'باقة صور إضافية (10)', 'Extra Photo Pack (10)', true, 100, 280, NULL, '10 صور إضافية معدلة باحتراف', '10 additional professionally edited photos', true, 300),
  ('photo-pack-50', 'باقة صور إضافية (50)', 'Extra Photo Pack (50)', false, 100, 1100, NULL, '50 صورة إضافية معدلة باحتراف', '50 additional professionally edited photos', true, 1100),
  ('pre-wedding-mini', 'جلسة تصوير ما قبل الزفاف (ساعة ونصف)', 'Pre-Wedding Mini Session', true, 40, 1200, NULL, 'جلسة تصوير قصيرة ومميزة قبل يوم الزفاف — 30 دقيقة، 15 صورة معدلة', 'Short, intimate shoot before the wedding day — 30 min, 15 edited photos', true, 1200),
  ('raw-files', 'تسليم الملفات الخام', 'Raw files delivery', true, 90, 900, NULL, NULL, NULL, true, 900),
  ('same-day-preview', 'معاينة يوم التصوير', 'Same-Day Preview', false, 100, 450, NULL, 'مشاهدة مجموعة مختارة من صورك في نفس يوم التصوير', 'View a curated selection of your photos on shoot day', true, 450),
  ('save-date', 'Save the Date', 'Save the Date', false, 110, 700, NULL, 'تجهيز فيديو دعوة للزواج', NULL, true, 700),
  ('second-photog', 'مصورة فيديو', 'Second photographer', false, 90, 1200, NULL, NULL, NULL, true, 1200),
  ('second-photographer', 'مصورة ثانية', 'Second Photographer', true, 70, 1200, NULL, 'مصورة أنثى ثانية لتغطية أشمل وأكثر تنوعاً', 'A second female photographer for wider, more varied coverage', true, 1200),
  ('video-full', 'فيديو سينمائي كامل (إضافة للكلاسيكية)', 'Full cinematic video (Classic add-on)', true, 30, 3200, NULL, NULL, NULL, true, 4800),
  ('video-short', 'فيديو سينمائي قصير (إضافة للكلاسيكية)', 'Short cinematic video (Classic add-on)', true, 10, 2200, NULL, NULL, NULL, true, 3400),
  ('videography', 'تصوير فيديو كامل', 'Full Videography', false, 100, 2500, NULL, 'تغطية فيديو احترافية كاملة للمناسبة', 'Full professional video coverage of the event', true, 2500)
on conflict (id) do update set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  active = excluded.active,
  sort_order = excluded.sort_order,
  price_sar = excluded.price_sar,
  icon_emoji = excluded.icon_emoji,
  description_ar = excluded.description_ar,
  description_en = excluded.description_en,
  is_active = excluded.is_active,
  price = excluded.price;


insert into public.packages (id, name_ar, name_en, price, duration_hours, edited_photos, album, video, description, features, badge, is_popular, active, included_addon_ids, sort_order, price_sar, edited_photos_count, album_type, includes_video, description_ar, description_en, is_active, display_order, photographer_count, female_photographers, delivery_days, features_ar, features_en, is_custom_base, editorial_photos)
values
  (1, 'باقة الخطوبة', 'Engagement Session', 2700, 2, 30, NULL, false, 'جلسة خطوبة رومانسية بأسلوب راقٍ — مثالية لإعلان البداية.', array['ساعتان من التصوير الاحترافي','٣٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','وحدة تخزين عدد لا محدود']::text[], 'الأساسي', false, true, array['save-date']::text[], 10, NULL, NULL, NULL, false, NULL, NULL, true, 0, 1, true, 5, array['30 صورة معدلة','مصورة أنثى','ملف رقمي JPG','تسليم 5 أيام']::text[], array['2 hours of professional photography','30 photos with basic edit (light + JPG conversion)','A curated selection of best frames','Digital storage in the couple''s names','Save-the-Date digital design — complimentary']::text[], false, 0),
  (2, 'الأساس المرن', 'Custom Foundation', 1800, 1, 20, NULL, false, 'الأساس المرن لباقتك المخصّصة — ابدئي من هنا وأضيفي ما يلائم مناسبتك.', array['ساعة واحدة من التصوير الاحترافي','٢٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','وحدة تخزين رقمية','أضيفي ساعات، فيديو، ألبوم، أو ليلة الحناء حسب احتياجك']::text[], NULL, false, true, array[]::text[], 0, NULL, NULL, NULL, false, NULL, NULL, true, 0, 1, true, 7, array['50 صورة معدلة','مصورة أنثى','ملف JPG كامل','تسليم 7 أيام']::text[], array['1 hour of professional photography','20 edited photos','Digital storage','Add hours, video, album, or henna night as you need']::text[], true, 0),
  (3, 'الباقة الكلاسيكية', 'Classic', 5500, 4, 300, 'ألبوم A4 ١٥ صفحة', false, 'الباقة المثالية للمناسبات الخاصة — ألبوم فاخر وذكريات تبقى، بفريق نسائي كامل.', array['٤ ساعات تغطية شاملة للحفل','مصوّرة رئيسية + مساعدة (فريق نسائي)','٣٠٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','ألبوم A4 بـ ١٥ صفحة — طباعة فاخرة','٥ صور عائلية معدّلة','وحدة تخزين بجميع الصور المعدّلة']::text[], NULL, false, true, array['second-photog']::text[], 30, NULL, NULL, NULL, false, NULL, NULL, true, 0, 1, true, 10, array['80 صورة معدلة','مصورة أنثى','ألبوم A4 (10 صفحات)','تسليم 10 أيام']::text[], array['4 hours of full event coverage','Lead photographer + assistant (all-female team)','300 photos with basic edit (light + JPG conversion)','A4 album, 15 pages — premium printing','5 retouched family photos','Digital storage of all edited images']::text[], false, 0),
  (4, 'الباقة الملكية', 'Royal', 11200, 5, 400, 'ألبوم A4 + ميني ألبوم', true, 'تجربة تصوير ملكية مع فيديو سينمائي قصير وألبومين فاخرين — الأكثر طلباً.', array['٥ ساعات تغطية شاملة للحفل','مصوّرة رئيسية + مصورة فيديو ','٤٠٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','٤ صور بتعديل تحريري احترافي (رتوش متقدم وتدرّج سينمائي)','فيديو سينمائي قصير (٣–٥ دقائق)','ألبوم A4 بـ ١٥ صفحة — طباعة فاخرة','اختيار ٣٥ لقطة للطباعة في الالبوم','ميني البوم','وحدة تخزين','مساعدة (فريق نسائي)']::text[], 'الأكثر طلباً', true, true, array['second-photog','video-short']::text[], 40, NULL, NULL, NULL, false, NULL, NULL, true, 0, 1, true, 14, array['100 صورة معدلة','مصورة أنثى','ألبوم فاخر + ميني','فيديو احترافي','تسليم 14 يوم']::text[], array['5 hours of full event coverage','Lead photographer + assistant (all-female team)','400 photos with basic edit (light + JPG conversion)','4 photos with editorial retouch (advanced retouching + cinematic grade)','Short cinematic video (3–5 minutes)','A4 album, 15 pages — premium printing','Mini family album','Digital storage in the couple''s names','Same-day preview (5 curated photos)']::text[], false, 4),
  (5, 'باقة التوقيع', 'Signature', 13000, 6, 500, 'ألبوم فاخر A3 ١٢ صفحة + ميني', true, 'الباقة الاحترافية الشاملة — فيديو سينمائي كامل، ألبوم A3 فاخر، وجلسة تحضيرات العروس.', array['٦ ساعات تغطية شاملة للحفل','مصوّرة رئيسية + مصورة فيديو','٥٠٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','٨ صور بتعديل تحريري احترافي (رتوش متقدم وتدرّج سينمائي)','فيديو سينمائي كامل','جلسة تصوير تحضيرات العروس','ألبوم فاخر A3 بـ ١٢ صفحة','ميني ألبوم','وحدة تخزين ','اختيار ٤٥ لقطة للطباعة في الالبوم','مساعدة (فريق نسائي)']::text[], 'فاخر', false, true, array['second-photog','video-full','bridal-prep','album-upgrade']::text[], 50, NULL, NULL, NULL, false, NULL, NULL, true, 0, 2, true, 14, array['120 صورة معدلة','مصورتان','ألبوم A3 (12 صفحة) + ميني','فيديو احترافي','تسليم 14 يوم']::text[], array['6 hours of full event coverage','Lead photographer + assistant (all-female team)','500 photos with basic edit (light + JPG conversion)','8 photos with editorial retouch (advanced retouching + cinematic grade)','Full cinematic video','Bridal-prep session','Premium A3 album, 12 pages','Mini family album','Engraved-name digital storage','Same-day preview (5 curated photos)']::text[], false, 8),
  (6, 'ATEMA Couture', 'ATEMA Couture', 20000, 8, 700, 'ألبوم فاخر A3 ٢٠ صفحة + ميني + لوحة جدارية', true, 'تجربة الفخامة الكاملة — كل تفاصيل اليوم بتوقيع كوتور حصري، من الحناء إلى الحفل.', array['تغطية شاملة كاملة للحفل (٨ ساعات)','مصوّرة رئيسية + مصورة فيديو','٧٠٠ صورة بتعديل أساسي (إضاءة + تحويل JPG)','١٢ صورة بتعديل تحريري احترافي (رتوش متقدم وتدرّج سينمائي)','فيديو سينمائي فاخر — تغطية كاملة ','جلسة تحضيرات العروس','تغطية ليلة الحناء ','ألبوم فاخر A3 بـ ٢٠ صفحة','ميني ألبوم فاخر','لوحة جدارية فنية مؤطرة','وحدة تخزين فاخرة','مساعدة (فريق نسائي)','تغطية جوال ','خدمة عملاء ومتابعة خاصة']::text[], 'الأفخم', true, true, array['second-photog','video-full','bridal-prep','album-upgrade','henna','kosha','--1780506890141']::text[], 60, NULL, NULL, NULL, false, NULL, NULL, true, 0, 2, true, 21, array['150 صورة معدلة','مصورتان','طباعة جدارية + ألبوم','فيديو سينمائي','تسليم 21 يوم']::text[], array['8 hours of full event coverage','Lead photographer + assistant (all-female team)','700 photos with basic edit (light + JPG conversion)','12 photos with editorial retouch (advanced retouching + cinematic grade)','Premium cinematic video — full event + henna night','Bridal-prep session','Henna-night coverage','Premium A3 album, 20 pages','Premium mini album','Framed art print','Premium engraved digital storage','Same-day preview (10 curated photos)','Dedicated concierge service']::text[], false, 12)
on conflict (id) do update set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  price = excluded.price,
  duration_hours = excluded.duration_hours,
  edited_photos = excluded.edited_photos,
  album = excluded.album,
  video = excluded.video,
  description = excluded.description,
  features = excluded.features,
  badge = excluded.badge,
  is_popular = excluded.is_popular,
  active = excluded.active,
  included_addon_ids = excluded.included_addon_ids,
  sort_order = excluded.sort_order,
  price_sar = excluded.price_sar,
  edited_photos_count = excluded.edited_photos_count,
  album_type = excluded.album_type,
  includes_video = excluded.includes_video,
  description_ar = excluded.description_ar,
  description_en = excluded.description_en,
  is_active = excluded.is_active,
  display_order = excluded.display_order,
  photographer_count = excluded.photographer_count,
  female_photographers = excluded.female_photographers,
  delivery_days = excluded.delivery_days,
  features_ar = excluded.features_ar,
  features_en = excluded.features_en,
  is_custom_base = excluded.is_custom_base,
  editorial_photos = excluded.editorial_photos;

