-- ATEMA STUDIO - Films curation table (July 2026)
--
-- Machine facts remain in public/videos/hls/manifest.json, generated by
-- npm run videos:prepare. This table stores the human curation that the
-- admin can hide/show or remove from the public /films page.

create table if not exists public.film_entries (
  manifest_id text primary key,
  slug        text not null unique,
  order_index integer not null default 100,
  chapter     text not null check (chapter in ('ceremony','portrait','detail','atelier')),
  title_ar    text not null,
  title_en    text not null,
  caption_ar  text not null default '',
  caption_en  text not null default '',
  published   boolean not null default true,
  featured    boolean not null default false,
  deleted_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.film_entries add column if not exists deleted_at timestamptz;
alter table public.film_entries add column if not exists featured boolean not null default false;
alter table public.film_entries add column if not exists updated_at timestamptz not null default now();

create index if not exists film_entries_public_idx
  on public.film_entries (published, deleted_at, order_index);

drop trigger if exists film_entries_updated_at on public.film_entries;
create trigger film_entries_updated_at
  before update on public.film_entries
  for each row execute function set_updated_at();

alter table public.film_entries enable row level security;

drop policy if exists "film_entries_public_read" on public.film_entries;
create policy "film_entries_public_read"
  on public.film_entries
  for select to anon, authenticated
  using (published = true and deleted_at is null);

drop policy if exists "film_entries_admin_all" on public.film_entries;
create policy "film_entries_admin_all"
  on public.film_entries
  for all to authenticated
  using (true) with check (true);

insert into public.film_entries (
  manifest_id, slug, order_index, chapter,
  title_ar, title_en, caption_ar, caption_en,
  published, featured
) values
  ('clip-01', 'golden-procession', 1, 'ceremony', 'دخول على ضوء الذهب', 'A Golden Procession', 'لقطة واسعة تحفظ لحظة العبور الأولى، حين يصبح الضوء جزءا من المراسم.', 'A wide moving frame for the first entrance, where light becomes part of the ceremony.', true, true),
  ('clip-02', 'veil-study-one', 2, 'portrait', 'دراسة الطرحة الأولى', 'Veil Study I', 'حركة هادئة حول القماش والوجه، مصممة لتبقى رقيقة لا صاخبة.', 'A quiet study of veil and face, made to feel delicate rather than loud.', true, true),
  ('clip-03', 'veil-study-continuity', 3, 'portrait', 'استمرار الطرحة', 'Veil Continuity', 'نسخة محفوظة من نفس النفس البصري، تبقي التسلسل كاملا في الأرشيف.', 'A preserved companion take that keeps the visual sequence complete in the archive.', true, false),
  ('clip-04', 'soft-turn', 4, 'portrait', 'التفاتة ناعمة', 'The Soft Turn', 'بورتريه متحرك يترك للالتفاتة وقتها، وللفستان مساحته في الصورة.', 'A moving portrait that gives the turn its time and the gown its full presence.', true, false),
  ('clip-05', 'quiet-gown', 5, 'portrait', 'هدوء الفستان', 'The Quiet Gown', 'لقطة قريبة من الحضور، لا تطارد الحركة بل تتركها تظهر بهدوء.', 'A close study of presence, letting motion arrive without forcing it.', true, false),
  ('clip-06', 'room-light', 6, 'atelier', 'ضوء الغرفة', 'Room Light', 'مشهد قصير يلتقط تنفس المكان قبل أن يبدأ الحدث الكبير.', 'A brief room study, catching the atmosphere before the larger moment begins.', true, false),
  ('clip-07', 'portrait-in-motion', 7, 'portrait', 'بورتريه في الحركة', 'Portrait in Motion', 'تكوين عمودي يحفظ ملامح العروس كما لو أنها تمر بين صورتين.', 'A vertical composition holding the bride as if she is moving between two stills.', true, false),
  ('clip-08', 'brief-glimmer', 8, 'detail', 'لمعة قصيرة', 'A Brief Glimmer', 'تفصيل عابر، لكنه يمنح الذاكرة ملمسا صغيرا لا يضيع.', 'A passing detail that gives the memory a small texture of its own.', true, false),
  ('clip-09', 'atelier-pause', 9, 'atelier', 'استراحة الأتيليه', 'Atelier Pause', 'لحظة ساكنة بين اللقطات، حيث يهدأ كل شيء قبل الكادر التالي.', 'A still pause between takes, where everything settles before the next frame.', true, false),
  ('clip-10', 'paired-detail-one', 10, 'detail', 'تفصيل مزدوج I', 'Paired Detail I', 'قرب محسوب من اليد والقماش، بنبرة وثائقية ناعمة.', 'A measured closeness to hand and fabric, held in a soft documentary tone.', true, false),
  ('clip-11', 'paired-detail-two', 11, 'detail', 'تفصيل مزدوج II', 'Paired Detail II', 'اللقطة الشقيقة تكمل الإيقاع، وتترك للتفاصيل أن تتكلم قليلا.', 'The companion frame completes the rhythm and lets the details speak quietly.', true, false),
  ('clip-12', 'wide-room-memory', 12, 'ceremony', 'ذاكرة المكان الواسعة', 'The Room Remembered Wide', 'مشهد أفقي يحفظ اتساع المكان، لا الأشخاص، ليبقى الجو هو البطل.', 'A horizontal room memory that keeps the atmosphere in the foreground.', true, false),
  ('clip-13', 'small-gesture', 13, 'detail', 'إشارة صغيرة', 'A Small Gesture', 'ومضة من الحركة، قصيرة بما يكفي لتشبه اللمحة الأولى.', 'A short flash of movement, brief enough to feel like a first glance.', true, false),
  ('clip-14', 'stillness-between', 14, 'atelier', 'السكون بين اللقطات', 'Stillness Between Frames', 'حين لا يحدث الكثير، تظهر أناقة المشهد كما هي.', 'When very little happens, the elegance of the scene becomes visible.', true, false),
  ('clip-15', 'prelude-one', 15, 'atelier', 'تمهيد I', 'Prelude I', 'جزء من التحضير الهادئ، يضع الإحساس قبل الحكاية.', 'A quiet preparation fragment, placing feeling before narrative.', true, false),
  ('clip-16', 'prelude-two', 16, 'atelier', 'تمهيد II', 'Prelude II', 'لقطة قريبة من الهدوء، تصلح كبداية ناعمة للفيلم.', 'A close, quiet frame that works like a soft beginning to the film.', true, false),
  ('clip-17', 'portrait-afterglow', 17, 'portrait', 'أثر البورتريه', 'Portrait Afterglow', 'الحركة هنا ليست استعراضا، بل أثر خفيف يبقى بعد الصورة.', 'Motion here is not performance, but a gentle trace left after the image.', true, false),
  ('clip-18', 'second-afterglow', 18, 'portrait', 'الأثر الثاني', 'Second Afterglow', 'صدى آخر لنفس اللغة، أكثر قربا من ملمس اللحظة.', 'Another echo of the same visual language, closer to the texture of the moment.', true, false),
  ('clip-19', 'closing-prelude', 19, 'atelier', 'تمهيد أخير', 'Closing Prelude', 'ختام صغير للمجموعة، يترك الباب مفتوحا للقطات القادمة.', 'A small closing note for the collection, leaving room for what comes next.', true, false)
on conflict (manifest_id) do update set
  slug        = excluded.slug,
  order_index = excluded.order_index,
  chapter     = excluded.chapter,
  title_ar    = excluded.title_ar,
  title_en    = excluded.title_en,
  caption_ar  = excluded.caption_ar,
  caption_en  = excluded.caption_en,
  featured    = excluded.featured
where public.film_entries.deleted_at is null;

select manifest_id, slug, published, deleted_at
  from public.film_entries
 order by order_index;
