// ATEMA STUDIO - Films registry.
//
// Split of responsibilities:
// - MACHINE FACTS: stream URL, poster, duration, dimensions, and renditions
//   live in public/videos/hls/manifest.json and are generated by
//   `npm run videos:prepare`. Never hand-edit the manifest.
// - HUMAN CURATION: bilingual titles, captions, chapters, and public ordering
//   live here. A new clip enters /films by running the video preparation
//   script, adding its manifest id below, and committing both.

export type FilmChapterKey = 'ceremony' | 'portrait' | 'detail' | 'atelier';

export interface FilmCuration {
  manifestId: string;
  slug: string;
  order: number;
  chapter: FilmChapterKey;
  title_ar: string;
  title_en: string;
  caption_ar: string;
  caption_en: string;
  featured?: boolean;
  published?: boolean;
}

export const FILM_CHAPTERS: Array<{ key: FilmChapterKey; ar: string; en: string }> = [
  { key: 'ceremony', ar: 'المشهد', en: 'Ceremony' },
  { key: 'portrait', ar: 'البورتريه', en: 'Portrait' },
  { key: 'detail', ar: 'التفاصيل', en: 'Details' },
  { key: 'atelier', ar: 'الأتيليه', en: 'Atelier' },
];

export const FILMS: FilmCuration[] = [
  {
    manifestId: 'clip-01',
    slug: 'golden-procession',
    order: 1,
    chapter: 'ceremony',
    title_ar: 'دخول على ضوء الذهب',
    title_en: 'A Golden Procession',
    caption_ar: 'لقطة واسعة تحفظ لحظة العبور الأولى، حين يصبح الضوء جزءا من المراسم.',
    caption_en: 'A wide moving frame for the first entrance, where light becomes part of the ceremony.',
    featured: true,
  },
  {
    manifestId: 'clip-02',
    slug: 'veil-study-one',
    order: 2,
    chapter: 'portrait',
    title_ar: 'دراسة الطرحة الأولى',
    title_en: 'Veil Study I',
    caption_ar: 'حركة هادئة حول القماش والوجه، مصممة لتبقى رقيقة لا صاخبة.',
    caption_en: 'A quiet study of veil and face, made to feel delicate rather than loud.',
    featured: true,
  },
  {
    manifestId: 'clip-03',
    slug: 'veil-study-continuity',
    order: 3,
    chapter: 'portrait',
    title_ar: 'استمرار الطرحة',
    title_en: 'Veil Continuity',
    caption_ar: 'نسخة محفوظة من نفس النفس البصري، تبقي التسلسل كاملا في الأرشيف.',
    caption_en: 'A preserved companion take that keeps the visual sequence complete in the archive.',
  },
  {
    manifestId: 'clip-04',
    slug: 'soft-turn',
    order: 4,
    chapter: 'portrait',
    title_ar: 'التفاتة ناعمة',
    title_en: 'The Soft Turn',
    caption_ar: 'بورتريه متحرك يترك للالتفاتة وقتها، وللفستان مساحته في الصورة.',
    caption_en: 'A moving portrait that gives the turn its time and the gown its full presence.',
  },
  {
    manifestId: 'clip-05',
    slug: 'quiet-gown',
    order: 5,
    chapter: 'portrait',
    title_ar: 'هدوء الفستان',
    title_en: 'The Quiet Gown',
    caption_ar: 'لقطة قريبة من الحضور، لا تطارد الحركة بل تتركها تظهر بهدوء.',
    caption_en: 'A close study of presence, letting motion arrive without forcing it.',
  },
  {
    manifestId: 'clip-06',
    slug: 'room-light',
    order: 6,
    chapter: 'atelier',
    title_ar: 'ضوء الغرفة',
    title_en: 'Room Light',
    caption_ar: 'مشهد قصير يلتقط تنفس المكان قبل أن يبدأ الحدث الكبير.',
    caption_en: 'A brief room study, catching the atmosphere before the larger moment begins.',
  },
  {
    manifestId: 'clip-07',
    slug: 'portrait-in-motion',
    order: 7,
    chapter: 'portrait',
    title_ar: 'بورتريه في الحركة',
    title_en: 'Portrait in Motion',
    caption_ar: 'تكوين عمودي يحفظ ملامح العروس كما لو أنها تمر بين صورتين.',
    caption_en: 'A vertical composition holding the bride as if she is moving between two stills.',
  },
  {
    manifestId: 'clip-08',
    slug: 'brief-glimmer',
    order: 8,
    chapter: 'detail',
    title_ar: 'لمعة قصيرة',
    title_en: 'A Brief Glimmer',
    caption_ar: 'تفصيل عابر، لكنه يمنح الذاكرة ملمسا صغيرا لا يضيع.',
    caption_en: 'A passing detail that gives the memory a small texture of its own.',
  },
  {
    manifestId: 'clip-09',
    slug: 'atelier-pause',
    order: 9,
    chapter: 'atelier',
    title_ar: 'استراحة الأتيليه',
    title_en: 'Atelier Pause',
    caption_ar: 'لحظة ساكنة بين اللقطات، حيث يهدأ كل شيء قبل الكادر التالي.',
    caption_en: 'A still pause between takes, where everything settles before the next frame.',
  },
  {
    manifestId: 'clip-10',
    slug: 'paired-detail-one',
    order: 10,
    chapter: 'detail',
    title_ar: 'تفصيل مزدوج I',
    title_en: 'Paired Detail I',
    caption_ar: 'قرب محسوب من اليد والقماش، بنبرة وثائقية ناعمة.',
    caption_en: 'A measured closeness to hand and fabric, held in a soft documentary tone.',
  },
  {
    manifestId: 'clip-11',
    slug: 'paired-detail-two',
    order: 11,
    chapter: 'detail',
    title_ar: 'تفصيل مزدوج II',
    title_en: 'Paired Detail II',
    caption_ar: 'اللقطة الشقيقة تكمل الإيقاع، وتترك للتفاصيل أن تتكلم قليلا.',
    caption_en: 'The companion frame completes the rhythm and lets the details speak quietly.',
  },
  {
    manifestId: 'clip-12',
    slug: 'wide-room-memory',
    order: 12,
    chapter: 'ceremony',
    title_ar: 'ذاكرة المكان الواسعة',
    title_en: 'The Room Remembered Wide',
    caption_ar: 'مشهد أفقي يحفظ اتساع المكان، لا الأشخاص، ليبقى الجو هو البطل.',
    caption_en: 'A horizontal room memory that keeps the atmosphere in the foreground.',
  },
  {
    manifestId: 'clip-13',
    slug: 'small-gesture',
    order: 13,
    chapter: 'detail',
    title_ar: 'إشارة صغيرة',
    title_en: 'A Small Gesture',
    caption_ar: 'ومضة من الحركة، قصيرة بما يكفي لتشبه اللمحة الأولى.',
    caption_en: 'A short flash of movement, brief enough to feel like a first glance.',
  },
  {
    manifestId: 'clip-14',
    slug: 'stillness-between',
    order: 14,
    chapter: 'atelier',
    title_ar: 'السكون بين اللقطات',
    title_en: 'Stillness Between Frames',
    caption_ar: 'حين لا يحدث الكثير، تظهر أناقة المشهد كما هي.',
    caption_en: 'When very little happens, the elegance of the scene becomes visible.',
  },
  {
    manifestId: 'clip-15',
    slug: 'prelude-one',
    order: 15,
    chapter: 'atelier',
    title_ar: 'تمهيد I',
    title_en: 'Prelude I',
    caption_ar: 'جزء من التحضير الهادئ، يضع الإحساس قبل الحكاية.',
    caption_en: 'A quiet preparation fragment, placing feeling before narrative.',
  },
  {
    manifestId: 'clip-16',
    slug: 'prelude-two',
    order: 16,
    chapter: 'atelier',
    title_ar: 'تمهيد II',
    title_en: 'Prelude II',
    caption_ar: 'لقطة قريبة من الهدوء، تصلح كبداية ناعمة للفيلم.',
    caption_en: 'A close, quiet frame that works like a soft beginning to the film.',
  },
  {
    manifestId: 'clip-17',
    slug: 'portrait-afterglow',
    order: 17,
    chapter: 'portrait',
    title_ar: 'أثر البورتريه',
    title_en: 'Portrait Afterglow',
    caption_ar: 'الحركة هنا ليست استعراضا، بل أثر خفيف يبقى بعد الصورة.',
    caption_en: 'Motion here is not performance, but a gentle trace left after the image.',
  },
  {
    manifestId: 'clip-18',
    slug: 'second-afterglow',
    order: 18,
    chapter: 'portrait',
    title_ar: 'الأثر الثاني',
    title_en: 'Second Afterglow',
    caption_ar: 'صدى آخر لنفس اللغة، أكثر قربا من ملمس اللحظة.',
    caption_en: 'Another echo of the same visual language, closer to the texture of the moment.',
  },
  {
    manifestId: 'clip-19',
    slug: 'closing-prelude',
    order: 19,
    chapter: 'atelier',
    title_ar: 'تمهيد أخير',
    title_en: 'Closing Prelude',
    caption_ar: 'ختام صغير للمجموعة، يترك الباب مفتوحا للقطات القادمة.',
    caption_en: 'A small closing note for the collection, leaving room for what comes next.',
  },
];
